=== stephcstn/projet_site_web_L1/xml/car.dtd
<!ELEMENT car (collection,couleurHistorique,caracteristiques)>
<!ATTLIST car 
    nom CDATA #REQUIRED
    modele CDATA #REQUIRED
    type (Berline | CoupÃ© | Cabriolet | Break | SUV | Crossover | Monospace | Pick-up | luxe | Supercar | Electrique | Hybride) #REQUIRED
    id ID #REQUIRED>

<!ELEMENT collection (prix,estimation)>

<!ELEMENT prix (#PCDATA)>

<!ELEMENT estimation (#PCDATA)>

<!ELEMENT couleurHistorique (histoire)>
<!ATTLIST couleurHistorique
    couleur CDATA #REQUIRED>

<!ELEMENT histoire (#PCDATA)>

<!ELEMENT caracteristiques (moteur,performances,autres,transmission,chassis,dimensions)>

<!ELEMENT moteur (type1,cylindree,puissance,couple)>
<!ATTLIST moteur
    energie (diesel | essence | electrique | ethanol | hydrogen) #REQUIRED
    nom CDATA #REQUIRED>

<!ELEMENT type1 (#PCDATA)>

<!ELEMENT cylindree (#PCDATA)>

<!ELEMENT puissance (#PCDATA)>

<!ELEMENT couple (#PCDATA)>

<!ELEMENT performances (acceleration+,vmax,consommation,emissions)>

<!ELEMENT acceleration (#PCDATA)>

<!ELEMENT vmax (#PCDATA)>

<!ELEMENT consommation (#PCDATA)>

<!ELEMENT emissions (#PCDATA)>

<!ELEMENT autres (quantiteProduite,dateSortie,dateFinDeProduction)>

<!ELEMENT quantiteProduite (#PCDATA)>

<!ELEMENT dateSortie (#PCDATA)>

<!ELEMENT dateFinDeProduction (#PCDATA)>

<!ELEMENT transmission (type2,rapport)>
<!ATTLIST transmission
    gearbox (manuelle | automatique | semi-automatique)>

<!ELEMENT type2 (#PCDATA)>

<!ELEMENT rapport (#PCDATA)>

<!ELEMENT chassis (suspension,freins)>

<!ELEMENT suspension (#PCDATA)>

<!ELEMENT freins (#PCDATA)>

<!ELEMENT dimensions (longueur,largeur,hauteur,reservoir,poidsVide)>

<!ELEMENT longueur (#PCDATA)>

<!ELEMENT largeur (#PCDATA)>

<!ELEMENT hauteur (#PCDATA)>

<!ELEMENT reservoir (#PCDATA)>

<!ELEMENT poidsVide (#PCDATA)>

=== stephcstn/projet_site_web_L1/XML/Enzo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "car.dtd">
<car nom="Ferrari" modele="Enzo" type="Supercar" id="car1">
    <collection>
        <prix>prix du véhicule neuf :  675 000 € TTC</prix>
        <estimation>prix du véhicule actuellement : 3 000 000 € TTC</estimation>
    </collection>
    <couleurHistorique couleur="rouge">
        <histoire>De ce fait, Enzo Ferrari, pilote, décide de créer sa propre écurie appelée 
         “La scuderia Ferrari” en 1929 et opte pour la couleur rouge. Ce n’est pas vraiment un 
         choix, c’est tout simplement un respect du règlement. Ainsi, les constructeurs italiens 
         de voitures de course comme Alfa Romeo, Maserati, Lancia et Ferrari ont commencé à teindre
         leurs voitures de course dans une nuance de rouge appelée la "Rossa Corsa" ("rouge course"). 
         C’est ainsi que la première auto d’Enzo Ferrari la Auto Avio 815 s’est parée de rouge.
        </histoire>
    </couleurHistorique>
    <caracteristiques>
        <moteur energie="essence" nom="F140 B Ferrari-Maserati">
            <type1>v12</type1>
            <cylindree>5998.80 cm3</cylindree>
            <puissance>660ch</puissance>
            <couple>655nm à 5500 trs/min</couple>
        </moteur>
        <performances>
            <acceleration>0 à 100km/h : 3,6s</acceleration>
            <acceleration>0 à 160km/h : 6,70s</acceleration>
            <acceleration>0 à 200km/h : 9,9s</acceleration>
            <vmax>353km/h</vmax>
            <consommation>normalisée : 23 l/100km</consommation>
            <emissions>Emissions CO2 : 545	g/km</emissions>
        </performances>
        <autres>
            <quantiteProduite>400</quantiteProduite>
            <dateSortie>2002</dateSortie>
            <dateFinDeProduction>2004</dateFinDeProduction>
        </autres>
        <transmission gearbox="manuelle">
            <type2>Propulsion</type2>
            <rapport>Séquentielle 6 rapports</rapport>
        </transmission>
        <chassis>
            <suspension> AV et AR : Triangles superposés</suspension>
            <freins> AV et AR : Disques ventilés en carbone céramique (380 mm)</freins>
        </chassis>
        <dimensions>
            <longueur>4,72m</longueur>
            <largeur>2,03m</largeur>
            <hauteur>1,14m</hauteur>
            <reservoir>110l</reservoir>
            <poidsVide>1375	kg</poidsVide>
        </dimensions>
    </caracteristiques>
</car>

=== stephcstn/projet_site_web_L1/XML/f40.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "car.dtd">
<car nom="Ferrari" modele="f40" type="Supercar" id="car2">
    <collection>
        <prix>prix du véhicule neuf :  250 000 € TTC</prix>
        <estimation>prix du véhicule actuellement : 3 000 000 € TTC</estimation>
    </collection>
    <couleurHistorique couleur ="rouge">
        <histoire>Couleur rouge : La Ferrari F40 est associée à une teinte de 
         rouge vif appelée "Rosso Corsa", qui évoque la passion pour la performance
         et la compétition. Cette couleur emblématique incarne l'héritage et la 
         tradition de la marque italienne, ainsi que la puissance brute et 
         l'élégance intemporelle de la F40. Choisir le "Rosso Corsa" pour sa 
         Ferrari F40 exprime l'authenticité, l'histoire et la passion pour la 
         conduite sportive et l'ingénierie automobile de pointe.
        </histoire>
    </couleurHistorique>
    <caracteristiques>
        <moteur energie="essence" nom="F120 D Ferrari" >
            <type1>6 cylindres à plat</type1>
            <cylindree>3299cc</cylindree>
            <puissance>360ch</puissance>
            <couple>459nm à 4500 trs/min</couple>
        </moteur>
        <performances>
            <acceleration>0 à 100km/h : 3,6s</acceleration>
            <acceleration>0 à 160km/h : 6,70s</acceleration>
            <acceleration>0 à 200km/h : 9,9s</acceleration>
            <vmax>353km/h</vmax>
            <consommation>normalisée : 23 l/100km</consommation>
            <emissions>Emissions CO2 : 545	g/km</emissions>
        </performances>
        <autres>
            <quantiteProduite>400</quantiteProduite>
            <dateSortie>2002</dateSortie>
            <dateFinDeProduction>2004</dateFinDeProduction>
        </autres>
        <transmission gearbox="manuelle">
            <type2>Propulsion</type2>
            <rapport>Séquentielle 6 rapports</rapport>
        </transmission>
        <chassis>
            <suspension> AV et AR : Triangles superposés</suspension>
            <freins> AV et AR : Disques ventilés en carbone céramique (380 mm)</freins>
        </chassis>
        <dimensions>
            <longueur>4,72m</longueur>
            <largeur>2,03m</largeur>
            <hauteur>1,14m</hauteur>
            <reservoir>110l</reservoir>
            <poidsVide>1375	kg</poidsVide>
        </dimensions>
    </caracteristiques>
</car>
